-- mock_turtle.lua
turtle = {
  forward   = function() print("[turtle] forward")  return true end,
  back      = function() print("[turtle] back")     return true end,
  up        = function() print("[turtle] up")       return true end,
  down      = function() print("[turtle] down")     return true end,
  turnLeft  = function() print("[turtle] turnLeft") return true end,
  turnRight = function() print("[turtle] turnRight")return true end,
  dig       = function() print("[turtle] dig")      return true end,
  digUp     = function() print("[turtle] digUp")    return true end,
  digDown   = function() print("[turtle] digDown")  return true end,
  place     = function() return true end,
  placeUp   = function() return true end,
  placeDown = function() return true end,
  detect    = function() return false end,
  detectUp  = function() return false end,
  detectDown = function() return false end,
  inspect   = function() return false, "no block" end,
  inspectUp = function() return false, "no block" end,
  inspectDown = function() return false, "no block" end,
  select    = function(slot) if slot > 16 or slot < 1 then return false end return true end,
  getItemDetail = function() return "minecraft:dirt" end,
  getFuelLevel = function() return 1000 end,
  refuel    = function() return true end,
}
